(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["main"],{

/***/ "./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./src/index.css":
/*!**************************************************************************************************************!*\
  !*** ./node_modules/css-loader??ref--7-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/index.css ***!
  \**************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

exports = module.exports = __webpack_require__(/*! ../node_modules/css-loader/lib/css-base.js */ "./node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.i, "body {\n  margin: 0;\n  padding: 0;\n  font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Roboto\", \"Oxygen\",\n    \"Ubuntu\", \"Cantarell\", \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\",\n    sans-serif;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\ncode {\n  font-family: source-code-pro, Menlo, Monaco, Consolas, \"Courier New\",\n    monospace;\n}\n", ""]);

// exports


/***/ }),

/***/ "./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./src/pagedraw/mainpush.css":
/*!**************************************************************************************************************************!*\
  !*** ./node_modules/css-loader??ref--7-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/pagedraw/mainpush.css ***!
  \**************************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

exports = module.exports = __webpack_require__(/*! ../../node_modules/css-loader/lib/css-base.js */ "./node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.i, "/* Generated by https://pagedraw.io/pages/14599 */\n.mainpush-mainpush-0 {\n    display: flex;\n    flex-direction: column;\n    flex-grow: 1;\n    background: rgb(255, 255, 255);\n}\n\n.mainpush-0 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-rectangle_4 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 13px;\n    padding-bottom: 15px;\n    background: rgb(235, 244, 251);\n}\n\n.mainpush-0-0-0 {\n    display: flex;\n    flex-shrink: 0;\n    padding-left: 13px;\n    padding-right: 17px;\n}\n\n.mainpush-findit_-3 {\n    width: 345px;\n    flex-shrink: 0;\n    font-family: Helvetica, Arial, sans-serif;\n    color: rgb(66, 73, 75);\n    font-size: 25px;\n    line-height: 16px;\n    letter-spacing: 0px;\n    font-weight: bold;\n    font-style: normal;\n    text-decoration: none;\n    text-align: center;\n    word-wrap: break-word;\n}\n\n.mainpush-1 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-rectangle-2 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 14px;\n    padding-bottom: 26px;\n    background: rgb(205, 226, 241);\n}\n\n.mainpush-1-0-0 {\n    display: flex;\n    flex-shrink: 0;\n    padding-left: 31px;\n    padding-right: 51px;\n}\n\n.mainpush-text-6 {\n    width: 293px;\n    flex-shrink: 0;\n    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n    color: rgb(255, 255, 255);\n    font-size: 14px;\n    line-height: 16px;\n    letter-spacing: 0px;\n    font-weight: bold;\n    font-style: normal;\n    text-decoration: none;\n    text-align: left;\n    word-wrap: break-word;\n}\n\n.mainpush-1-0-1 {\n    display: flex;\n    flex-shrink: 0;\n    margin-top: 13px;\n    padding-left: 31px;\n    padding-right: 51px;\n}\n\n.mainpush-text-5 {\n    width: 293px;\n    flex-shrink: 0;\n    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n    color: rgb(255, 255, 255);\n    font-size: 14px;\n    line-height: 16px;\n    letter-spacing: 0px;\n    font-weight: normal;\n    font-style: normal;\n    text-decoration: none;\n    text-align: left;\n    word-wrap: break-word;\n}\n\n.mainpush-1-0-2 {\n    display: flex;\n    flex-shrink: 0;\n    margin-top: 12px;\n    padding-left: 31px;\n    padding-right: 51px;\n}\n\n.mainpush-text-7 {\n    width: 293px;\n    flex-shrink: 0;\n    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n    color: rgb(255, 255, 255);\n    font-size: 14px;\n    line-height: 16px;\n    letter-spacing: 0px;\n    font-weight: normal;\n    font-style: normal;\n    text-decoration: none;\n    text-align: left;\n    word-wrap: break-word;\n}\n\n.mainpush-1-0-3 {\n    display: flex;\n    flex-shrink: 0;\n    margin-top: 18px;\n    padding-left: 31px;\n    padding-right: 29px;\n}\n\n.mainpush-image-9 {\n    width: 315px;\n    height: 124px;\n    flex-shrink: 0;\n    border-width: 0px;\n}\n\n.mainpush-2 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-rectangle-3 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 15px;\n    padding-bottom: 35px;\n    background: rgb(170, 197, 216);\n}\n\n.mainpush-2-0-0 {\n    display: flex;\n    flex-shrink: 0;\n    padding-left: 30px;\n    padding-right: 32px;\n}\n\n.mainpush-2-0-0-0 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 14px;\n    padding-bottom: 12px;\n}\n\n.mainpush-2-0-0-0-0 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-text-8 {\n    width: 249px;\n    flex-shrink: 0;\n    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n    color: rgb(255, 255, 255);\n    font-size: 14px;\n    line-height: 16px;\n    letter-spacing: 0px;\n    font-weight: bold;\n    font-style: normal;\n    text-decoration: none;\n    text-align: left;\n    word-wrap: break-word;\n}\n\n.mainpush-image_2 {\n    width: 50px;\n    height: 42px;\n    flex-shrink: 0;\n    margin-left: 14px;\n    border-width: 0px;\n}\n\n.mainpush-3 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-rectangle_2 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 27px;\n    padding-bottom: 23px;\n    background: rgb(137, 158, 173);\n}\n\n.mainpush-3-0-0 {\n    display: flex;\n    flex-shrink: 0;\n    padding-left: 30px;\n    padding-right: 32px;\n}\n\n.mainpush-3-0-0-0 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 5px;\n    padding-bottom: 21px;\n}\n\n.mainpush-3-0-0-0-0 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-text-78 {\n    width: 258px;\n    flex-shrink: 0;\n    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n    color: rgb(255, 255, 255);\n    font-size: 14px;\n    line-height: 16px;\n    letter-spacing: 0px;\n    font-weight: bold;\n    font-style: normal;\n    text-decoration: none;\n    text-align: left;\n    word-wrap: break-word;\n}\n\n.mainpush-image_3 {\n    width: 51px;\n    height: 42px;\n    flex-shrink: 0;\n    margin-left: 4px;\n    background: #D8D8D8;\n}\n\n.mainpush-4 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-rectangle-8 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 25px;\n    padding-bottom: 25px;\n    background: rgb(73, 85, 88);\n}\n\n.mainpush-4-0-0 {\n    display: flex;\n    flex-shrink: 0;\n    padding-left: 30px;\n    padding-right: 32px;\n}\n\n.mainpush-4-0-0-0 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 13px;\n    padding-bottom: 13px;\n}\n\n.mainpush-4-0-0-0-0 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-lol_-6 {\n    width: 258px;\n    flex-shrink: 0;\n    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n    color: #FFFFFF;\n    font-size: 14px;\n    line-height: 16px;\n    letter-spacing: 0px;\n    font-weight: bold;\n    font-style: normal;\n    text-decoration: none;\n    text-align: left;\n    word-wrap: break-word;\n}\n\n.mainpush-image_4 {\n    width: 51px;\n    height: 42px;\n    flex-shrink: 0;\n    margin-left: 4px;\n    background: #D8D8D8;\n}\n\n.mainpush-5 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-rectangle_3 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 25px;\n    padding-bottom: 25px;\n    background: rgb(49, 53, 55);\n}\n\n.mainpush-5-0-0 {\n    display: flex;\n    flex-shrink: 0;\n    padding-left: 30px;\n    padding-right: 32px;\n}\n\n.mainpush-5-0-0-0 {\n    display: flex;\n    flex-direction: column;\n    padding-top: 13px;\n    padding-bottom: 13px;\n}\n\n.mainpush-5-0-0-0-0 {\n    display: flex;\n    flex-shrink: 0;\n}\n\n.mainpush-lol_-7 {\n    width: 258px;\n    flex-shrink: 0;\n    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n    color: #FFFFFF;\n    font-size: 14px;\n    line-height: 16px;\n    letter-spacing: 0px;\n    font-weight: bold;\n    font-style: normal;\n    text-decoration: none;\n    text-align: left;\n    word-wrap: break-word;\n}\n\n.mainpush-image_5 {\n    width: 51px;\n    height: 42px;\n    flex-shrink: 0;\n    margin-left: 4px;\n    background: #D8D8D8;\n}\n\n.mainpush-6 {\n    flex-shrink: 0;\n    flex-grow: 1;\n    flex-basis: 0px;\n}\n\n* {\n    box-sizing: border-box;\n}\n\nbody {\n    margin: 0;\n}\n\nbutton:hover {\n    cursor: pointer;\n}\n\na {\n    text-decoration: none;\n    color: inherit;\n}\n\n.pd-onhover-parent >.pd-onhover {\n    display: none;\n}\n\n.pd-onhover-parent:hover > * {\n    display: none;\n}\n\n.pd-onhover-parent:hover > .pd-onhover {\n    display: flex;\n}\n\n.pd-onactive-parent > .pd-onactive {\n    display: none;\n}\n\n.pd-onactive-parent:active > * {\n    display: none;\n}\n\n.pd-onactive-parent:active > .pd-onactive {\n    display: flex;\n}\n\n.pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {\n    display: none;\n}\n", ""]);

// exports


/***/ }),

/***/ "./src/App.js":
/*!********************!*\
  !*** ./src/App.js ***!
  \********************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/classCallCheck */ "./node_modules/@babel/runtime/helpers/esm/classCallCheck.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/createClass */ "./node_modules/@babel/runtime/helpers/esm/createClass.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_possibleConstructorReturn__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn */ "./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_getPrototypeOf__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/getPrototypeOf */ "./node_modules/@babel/runtime/helpers/esm/getPrototypeOf.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_inherits__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/inherits */ "./node_modules/@babel/runtime/helpers/esm/inherits.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_assertThisInitialized__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/assertThisInitialized */ "./node_modules/@babel/runtime/helpers/esm/assertThisInitialized.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_6___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_6__);
/* harmony import */ var _myHaverSine_js__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ./myHaverSine.js */ "./src/myHaverSine.js");
/* harmony import */ var _pagedraw_mainpush__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! ./pagedraw/mainpush */ "./src/pagedraw/mainpush.js");
/* harmony import */ var _Lokation__WEBPACK_IMPORTED_MODULE_9__ = __webpack_require__(/*! ./Lokation */ "./src/Lokation.js");
/* harmony import */ var _GeoPushComponent_js__WEBPACK_IMPORTED_MODULE_10__ = __webpack_require__(/*! ./GeoPushComponent.js */ "./src/GeoPushComponent.js");






var _jsxFileName = "/Users/kaspermaansson/Documents/ITU/1. Semester/Prototyping af interaktive teknologier/VSC/OPG3/src/App.js";




 //HARDCODEDE LOKATIONER     ||     navn, latitude, longitude, åbningstider, billede-link

var lokation3 = new _Lokation__WEBPACK_IMPORTED_MODULE_9__["default"]('Analog', 55.660039, 12.590965, '07.50 - 16.00', 'https://placekitten.com/600/400');
var lokation2 = new _Lokation__WEBPACK_IMPORTED_MODULE_9__["default"]('ScrollBar', 55.659384, 12.590724, 'lukket :(', 'https://placekitten.com/204/128');
var lokation1 = new _Lokation__WEBPACK_IMPORTED_MODULE_9__["default"]('EatIT', 55.659325, 12.591203, '07.30 - 16.00', 'https://placekitten.com/300/200');
var lokation4 = new _Lokation__WEBPACK_IMPORTED_MODULE_9__["default"]('Fakta', 55.559325, 12.551203, '00.30 - 13.00', 'https://placekitten.com/300/200'); //ARRAY MED LOKATIONER

var geoLokationer = new Array(_Lokation__WEBPACK_IMPORTED_MODULE_9__["default"]);
geoLokationer = [lokation1, lokation2, lokation3, lokation4];

var App =
/*#__PURE__*/
function (_Component) {
  Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_inherits__WEBPACK_IMPORTED_MODULE_4__["default"])(App, _Component);

  function App(props) {
    var _this;

    Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_0__["default"])(this, App);

    _this = Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_possibleConstructorReturn__WEBPACK_IMPORTED_MODULE_2__["default"])(this, Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_getPrototypeOf__WEBPACK_IMPORTED_MODULE_3__["default"])(App).call(this, props));
    _this.state = {
      latitude: 0,
      longitude: 0
    };
    _this.e = null;
    _this.updatePostionData = _this.updatePostionData.bind(Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_assertThisInitialized__WEBPACK_IMPORTED_MODULE_5__["default"])(Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_assertThisInitialized__WEBPACK_IMPORTED_MODULE_5__["default"])(_this)));
    _this.geoError = _this.geoError.bind(Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_assertThisInitialized__WEBPACK_IMPORTED_MODULE_5__["default"])(Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_assertThisInitialized__WEBPACK_IMPORTED_MODULE_5__["default"])(_this)));
    return _this;
  } //funktioner til Geo, gennemløber array med Lokationer og udregner distancen fra nuværende position


  Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_1__["default"])(App, [{
    key: "updatePostionData",
    value: function updatePostionData(position) {
      for (var i = 0; i < geoLokationer.length; i++) {
        var theDistance = Object(_myHaverSine_js__WEBPACK_IMPORTED_MODULE_7__["default"])(position.coords.latitude, geoLokationer[i].latitude, position.coords.longitude, geoLokationer[i].longitude);
        geoLokationer[i].distanceTo = theDistance;
      }

      this.setState({
        longitude: position.coords.longitude,
        latitude: position.coords.longitude
      });
    } //GEO ERROR (?)

  }, {
    key: "geoError",
    value: function geoError(err) {
      this.e = err.message;
    } //METODE DER BRUGES I "FINDCLOSESTLOKATION"

  }, {
    key: "dynamicSort",
    value: function dynamicSort(property) {
      var sortOrder = 1;

      if (property[0] === "-") {
        sortOrder = -1;
        property = property.substr(1);
      }

      return function (a, b) {
        var result = a[property] < b[property] ? -1 : a[property] > b[property] ? 1 : 0;
        return result * sortOrder;
      };
    } //METODE DER SORTERER VORES ARRAY VIA "DYNAMIC SORT" EFTER DISTANCE OG RETURNERER DET, SORTERET

  }, {
    key: "findClosestLokation",
    value: function findClosestLokation(lokationer) {
      lokationer.sort(this.dynamicSort('distanceTo'));
      return lokationer;
    } //DET DER VISES PÅ SKÆRMEN

  }, {
    key: "render",
    value: function render() {
      return react__WEBPACK_IMPORTED_MODULE_6___default.a.createElement("div", {
        __source: {
          fileName: _jsxFileName,
          lineNumber: 69
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_6___default.a.createElement(_pagedraw_mainpush__WEBPACK_IMPORTED_MODULE_8__["default"] //lukkes efter sidste textTo...
      // TÆTTESTE LOKATION - INFO
      , {
        textToFirstTitle: 'Tættest på dig: ' + this.findClosestLokation(geoLokationer)[0].lokationName,
        textToFirstDist: 'Distance: ' + Math.round(1000 * this.findClosestLokation(geoLokationer)[0].distanceTo) + 'm',
        textToFirstDesc: 'Åbningstid i dag: ' + geoLokationer[0].openingHrs,
        ImgToFirst: geoLokationer[0].image // 2. TÆTTESTE LOKATION - INFO
        ,
        textToSecond: 'Lidt længere væk: ' + this.findClosestLokation(geoLokationer)[1].lokationName + ' (' + Math.round(1000 * this.findClosestLokation(geoLokationer)[1].distanceTo) + 'm)',
        ImgToSecond: geoLokationer[1].image // 3. TÆTTESTE LOKATION - INFO     
        ,
        textToThird: 'Længst væk: ' + this.findClosestLokation(geoLokationer)[2].lokationName + ' (' + Math.round(1000 * this.findClosestLokation(geoLokationer)[2].distanceTo) + 'm)',
        textToLast: 'lol: ' + this.findClosestLokation(geoLokationer)[3].lokationName + ': åbningstider: ' + geoLokationer[3].openingHrs,
        __source: {
          fileName: _jsxFileName,
          lineNumber: 70
        },
        __self: this
      }), react__WEBPACK_IMPORTED_MODULE_6___default.a.createElement(_GeoPushComponent_js__WEBPACK_IMPORTED_MODULE_10__["default"], {
        GeoUpdatePositionData: this.updatePostionData,
        GeoError: this.geoError,
        __source: {
          fileName: _jsxFileName,
          lineNumber: 91
        },
        __self: this
      }));
    }
  }]);

  return App;
}(react__WEBPACK_IMPORTED_MODULE_6__["Component"]);

/* harmony default export */ __webpack_exports__["default"] = (App);

/***/ }),

/***/ "./src/GeoPushComponent.js":
/*!*********************************!*\
  !*** ./src/GeoPushComponent.js ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/classCallCheck */ "./node_modules/@babel/runtime/helpers/esm/classCallCheck.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/createClass */ "./node_modules/@babel/runtime/helpers/esm/createClass.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_possibleConstructorReturn__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn */ "./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_getPrototypeOf__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/getPrototypeOf */ "./node_modules/@babel/runtime/helpers/esm/getPrototypeOf.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_inherits__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/inherits */ "./node_modules/@babel/runtime/helpers/esm/inherits.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_5___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_5__);







var GeoPushComponent =
/*#__PURE__*/
function (_Component) {
  Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_inherits__WEBPACK_IMPORTED_MODULE_4__["default"])(GeoPushComponent, _Component);

  function GeoPushComponent(props) {
    var _this;

    Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_0__["default"])(this, GeoPushComponent);

    _this = Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_possibleConstructorReturn__WEBPACK_IMPORTED_MODULE_2__["default"])(this, Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_getPrototypeOf__WEBPACK_IMPORTED_MODULE_3__["default"])(GeoPushComponent).call(this, props));
    _this.state = {};
    _this.GeoOptions = {
      enableHighAccuracy: true,
      timeout: 20000,
      maximumAge: 0,
      distanceFilter: 1
    };
    return _this;
  } // take function from owner of componemt as prop and assign it as callback 
  // Playing it nice - waiting for compoennt to  mount the DOM eventhough we don't have anything to display as component


  Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_1__["default"])(GeoPushComponent, [{
    key: "componentDidMount",
    value: function componentDidMount() {
      console.log('ComponentDidMount MyGeo2');
      console.log(this.props);
      this.watchId = navigator.geolocation.watchPosition(this.props.GeoUpdatePositionData, this.props.GeoError, this.GeoOptions);
    } // And cleaning up when we are done using the component

  }, {
    key: "componentWillUnmount",
    value: function componentWillUnmount() {
      navigator.geolocation.clearWatch(this.watchId);
    } // A special kind of component that doesn't actually srender anything but ship results to owner of the component
    // Just want to be part of the React component family

  }, {
    key: "render",
    value: function render() {
      return null;
    }
  }]);

  return GeoPushComponent;
}(react__WEBPACK_IMPORTED_MODULE_5__["Component"]);

/* harmony default export */ __webpack_exports__["default"] = (GeoPushComponent);

/***/ }),

/***/ "./src/Lokation.js":
/*!*************************!*\
  !*** ./src/Lokation.js ***!
  \*************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/classCallCheck */ "./node_modules/@babel/runtime/helpers/esm/classCallCheck.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_possibleConstructorReturn__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn */ "./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_getPrototypeOf__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/getPrototypeOf */ "./node_modules/@babel/runtime/helpers/esm/getPrototypeOf.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_inherits__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/inherits */ "./node_modules/@babel/runtime/helpers/esm/inherits.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_4___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_4__);




 //import haverDistance from './myHaverSine.js';
//import GeoPushComponent from './GeoPushComponent.js';

var Lokation =
/*#__PURE__*/
function (_React$Component) {
  Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_inherits__WEBPACK_IMPORTED_MODULE_3__["default"])(Lokation, _React$Component);

  function Lokation(lokationName, latitude, longitude, openingHrs, image) {
    var _this;

    Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_0__["default"])(this, Lokation);

    _this = Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_possibleConstructorReturn__WEBPACK_IMPORTED_MODULE_1__["default"])(this, Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_getPrototypeOf__WEBPACK_IMPORTED_MODULE_2__["default"])(Lokation).call(this));
    _this.distanceTo = 0;
    _this.lokationName = lokationName;
    _this.latitude = latitude;
    _this.longitude = longitude;
    _this.openingHrs = openingHrs;
    _this.image = image;
    return _this;
  }

  return Lokation;
}(react__WEBPACK_IMPORTED_MODULE_4___default.a.Component);

/* harmony default export */ __webpack_exports__["default"] = (Lokation);

/***/ }),

/***/ "./src/index.css":
/*!***********************!*\
  !*** ./src/index.css ***!
  \***********************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {


var content = __webpack_require__(/*! !../node_modules/css-loader??ref--7-oneOf-3-1!../node_modules/postcss-loader/src??postcss!./index.css */ "./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./src/index.css");

if(typeof content === 'string') content = [[module.i, content, '']];

var transform;
var insertInto;



var options = {"hmr":true}

options.transform = transform
options.insertInto = undefined;

var update = __webpack_require__(/*! ../node_modules/style-loader/lib/addStyles.js */ "./node_modules/style-loader/lib/addStyles.js")(content, options);

if(content.locals) module.exports = content.locals;

if(true) {
	module.hot.accept(/*! !../node_modules/css-loader??ref--7-oneOf-3-1!../node_modules/postcss-loader/src??postcss!./index.css */ "./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./src/index.css", function() {
		var newContent = __webpack_require__(/*! !../node_modules/css-loader??ref--7-oneOf-3-1!../node_modules/postcss-loader/src??postcss!./index.css */ "./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./src/index.css");

		if(typeof newContent === 'string') newContent = [[module.i, newContent, '']];

		var locals = (function(a, b) {
			var key, idx = 0;

			for(key in a) {
				if(!b || a[key] !== b[key]) return false;
				idx++;
			}

			for(key in b) idx--;

			return idx === 0;
		}(content.locals, newContent.locals));

		if(!locals) throw new Error('Aborting CSS HMR due to changed css-modules locals.');

		update(newContent);
	});

	module.hot.dispose(function() { update(); });
}

/***/ }),

/***/ "./src/index.js":
/*!**********************!*\
  !*** ./src/index.js ***!
  \**********************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! react-dom */ "./node_modules/react-dom/index.js");
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(react_dom__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */ var _index_css__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./index.css */ "./src/index.css");
/* harmony import */ var _index_css__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(_index_css__WEBPACK_IMPORTED_MODULE_2__);
/* harmony import */ var _App__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./App */ "./src/App.js");
var _jsxFileName = "/Users/kaspermaansson/Documents/ITU/1. Semester/Prototyping af interaktive teknologier/VSC/OPG3/src/index.js";




react_dom__WEBPACK_IMPORTED_MODULE_1___default.a.render(react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_App__WEBPACK_IMPORTED_MODULE_3__["default"], {
  __source: {
    fileName: _jsxFileName,
    lineNumber: 6
  },
  __self: undefined
}), document.getElementById('root'));

/***/ }),

/***/ "./src/myHaverSine.js":
/*!****************************!*\
  !*** ./src/myHaverSine.js ***!
  \****************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return haverDistance; });
// Returner distance mellem 2 lokationer (koordinater angivet) i kilometer
function haverDistance(lat1, lat2, lon1, lon2) {
  var R = 6371; // km radius of planet earth

  var dLat = toRad(lat2 - lat1);
  var dLon = toRad(lon2 - lon1);
  var lat1r = toRad(lat1);
  var lat2r = toRad(lat2);
  var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.sin(dLon / 2) * Math.sin(dLon / 2) * Math.cos(lat1r) * Math.cos(lat2r);
  var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  var d = R * c;
  return d; // i kilometer
}

function toRad(Value) {
  // Converts numeric degrees to radians
  return Value * Math.PI / 180;
}

/***/ }),

/***/ "./src/pagedraw/mainpush.css":
/*!***********************************!*\
  !*** ./src/pagedraw/mainpush.css ***!
  \***********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {


var content = __webpack_require__(/*! !../../node_modules/css-loader??ref--7-oneOf-3-1!../../node_modules/postcss-loader/src??postcss!./mainpush.css */ "./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./src/pagedraw/mainpush.css");

if(typeof content === 'string') content = [[module.i, content, '']];

var transform;
var insertInto;



var options = {"hmr":true}

options.transform = transform
options.insertInto = undefined;

var update = __webpack_require__(/*! ../../node_modules/style-loader/lib/addStyles.js */ "./node_modules/style-loader/lib/addStyles.js")(content, options);

if(content.locals) module.exports = content.locals;

if(true) {
	module.hot.accept(/*! !../../node_modules/css-loader??ref--7-oneOf-3-1!../../node_modules/postcss-loader/src??postcss!./mainpush.css */ "./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./src/pagedraw/mainpush.css", function() {
		var newContent = __webpack_require__(/*! !../../node_modules/css-loader??ref--7-oneOf-3-1!../../node_modules/postcss-loader/src??postcss!./mainpush.css */ "./node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./src/pagedraw/mainpush.css");

		if(typeof newContent === 'string') newContent = [[module.i, newContent, '']];

		var locals = (function(a, b) {
			var key, idx = 0;

			for(key in a) {
				if(!b || a[key] !== b[key]) return false;
				idx++;
			}

			for(key in b) idx--;

			return idx === 0;
		}(content.locals, newContent.locals));

		if(!locals) throw new Error('Aborting CSS HMR due to changed css-modules locals.');

		update(newContent);
	});

	module.hot.dispose(function() { update(); });
}

/***/ }),

/***/ "./src/pagedraw/mainpush.js":
/*!**********************************!*\
  !*** ./src/pagedraw/mainpush.js ***!
  \**********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return Mainpush; });
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/classCallCheck */ "./node_modules/@babel/runtime/helpers/esm/classCallCheck.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/createClass */ "./node_modules/@babel/runtime/helpers/esm/createClass.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_possibleConstructorReturn__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn */ "./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_getPrototypeOf__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/getPrototypeOf */ "./node_modules/@babel/runtime/helpers/esm/getPrototypeOf.js");
/* harmony import */ var _Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_inherits__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/inherits */ "./node_modules/@babel/runtime/helpers/esm/inherits.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_5___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_5__);
/* harmony import */ var _mainpush_css__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ./mainpush.css */ "./src/pagedraw/mainpush.css");
/* harmony import */ var _mainpush_css__WEBPACK_IMPORTED_MODULE_6___default = /*#__PURE__*/__webpack_require__.n(_mainpush_css__WEBPACK_IMPORTED_MODULE_6__);





var _jsxFileName = "/Users/kaspermaansson/Documents/ITU/1. Semester/Prototyping af interaktive teknologier/VSC/OPG3/src/pagedraw/mainpush.js";
// Generated by https://pagedraw.io/pages/14599



var Mainpush =
/*#__PURE__*/
function (_React$Component) {
  Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_inherits__WEBPACK_IMPORTED_MODULE_4__["default"])(Mainpush, _React$Component);

  function Mainpush() {
    Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_0__["default"])(this, Mainpush);

    return Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_possibleConstructorReturn__WEBPACK_IMPORTED_MODULE_2__["default"])(this, Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_getPrototypeOf__WEBPACK_IMPORTED_MODULE_3__["default"])(Mainpush).apply(this, arguments));
  }

  Object(_Users_kaspermaansson_Documents_ITU_1_Semester_Prototyping_af_interaktive_teknologier_VSC_OPG3_node_modules_babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_1__["default"])(Mainpush, [{
    key: "render",
    value: function render() {
      return react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-mainpush-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 9
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 10
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-rectangle_4",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 11
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 12
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-findit_-3",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 13
        },
        __self: this
      }, "FindIT")))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-1",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 17
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-rectangle-2",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 18
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-1-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 19
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-text-6",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 20
        },
        __self: this
      }, this.props.textToFirstTitle)), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-1-0-1",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 24
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-text-5",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 25
        },
        __self: this
      }, this.props.textToFirstDist)), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-1-0-2",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 29
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-text-7",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 30
        },
        __self: this
      }, this.props.textToFirstDesc)), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-1-0-3",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 34
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("img", {
        src: this.props.ImgToFirst,
        className: "mainpush-image-9",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 35
        },
        __self: this
      })))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-2",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 39
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-rectangle-3",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 40
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-2-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 41
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-2-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 42
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-2-0-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 43
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-text-8",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 44
        },
        __self: this
      }, this.props.textToSecond))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("img", {
        src: this.props.ImgToSecond,
        className: "mainpush-image_2",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 49
        },
        __self: this
      })))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-3",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 53
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-rectangle_2",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 54
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-3-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 55
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-3-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 56
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-3-0-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 57
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-text-78",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 58
        },
        __self: this
      }, this.props.textToThird))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-image_3",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 63
        },
        __self: this
      })))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-4",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 67
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-rectangle-8",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 68
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-4-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 69
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-4-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 70
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-4-0-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 71
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-lol_-6",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 72
        },
        __self: this
      }, this.props.textToLast))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-image_4",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 77
        },
        __self: this
      })))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-5",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 81
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-rectangle_3",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 82
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-5-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 83
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-5-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 84
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-5-0-0-0-0",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 85
        },
        __self: this
      }, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-lol_-7",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 86
        },
        __self: this
      }, this.props.textToLast))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-image_5",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 91
        },
        __self: this
      })))), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("div", {
        className: "mainpush-6",
        __source: {
          fileName: _jsxFileName,
          lineNumber: 95
        },
        __self: this
      }));
    }
  }]);

  return Mainpush;
}(react__WEBPACK_IMPORTED_MODULE_5___default.a.Component);


;

/***/ }),

/***/ 0:
/*!**********************************************************************************!*\
  !*** multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js ***!
  \**********************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

__webpack_require__(/*! /Users/kaspermaansson/Documents/ITU/1. Semester/Prototyping af interaktive teknologier/VSC/OPG3/node_modules/react-dev-utils/webpackHotDevClient.js */"./node_modules/react-dev-utils/webpackHotDevClient.js");
module.exports = __webpack_require__(/*! /Users/kaspermaansson/Documents/ITU/1. Semester/Prototyping af interaktive teknologier/VSC/OPG3/src/index.js */"./src/index.js");


/***/ })

},[[0,"runtime~main",0]]]);
//# sourceMappingURL=main.chunk.js.map