// Generated by https://pagedraw.io/pages/14599
import React from 'react';
import './mainpush.css';


export default class Mainpush extends React.Component {
  render() {
    return (
      <div className="mainpush-mainpush-0">
          <div className="mainpush-0">
              <div className="mainpush-spis_restaden_-3">
                  {"SPIS ØRESTADEN"}
              </div>
          </div>
          <div className="mainpush-1">
              <div className="mainpush-rectangle-2">
                  <div className="mainpush-1-0-0">
                      <div className="mainpush-text-6">
                          { this.props.textToFirstTitle }
                      </div>
                  </div>
                  <div className="mainpush-1-0-1">
                      <div className="mainpush-text-5">
                          { this.props.textToFirstDist }
                      </div>
                  </div>
                  <div className="mainpush-1-0-2">
                      <div className="mainpush-text-7">
                          { this.props.textToFirstDesc }
                      </div>
                  </div>
              </div>
          </div>
          <div className="mainpush-2">
              <div className="mainpush-rectangle-3">
                  <div className="mainpush-2-0-0">
                      <div className="mainpush-text-8">
                          {"Lidt længere væk:"}
                      </div>
                  </div>
                  <div className="mainpush-2-0-1">
                      <div className="mainpush-text-9">
                          { this.props.textToSecond }
                      </div>
                  </div>
              </div>
          </div>
          <div className="mainpush-3">
              <div className="mainpush-rectangle-8">
                  <div className="mainpush-3-0-0">
                      <div className="mainpush-text-78">{"Længst væk:"}</div>
                  </div>
                  <div className="mainpush-3-0-1">
                      <div className="mainpush-text-4">
                          { this.props.textToThird }
                      </div>
                  </div>
              </div>
          </div>
          <div className="mainpush-4" /> 
      </div>
    );
  }
};
