// Generated by https://pagedraw.io/pages/14599
import React from 'react';
import './mainpull.css';


export default class Mainpull extends React.Component {
  render() {
    return (
      <div className="mainpull-mainpull-0" /> 
    );
  }
};
