// Generated by https://pagedraw.io/pages/14599
import React from 'react';
import './secondarypush.css';


export default class Secondarypush extends React.Component {
  render() {
    return (
      <div className="secondarypush-secondarypush-0">
          <div className="secondarypush-0">
              <div className="secondarypush-rectangle_4">
                  <div className="secondarypush-0-0-0">
                      <div className="secondarypush-findit_-9">FindIT</div>
                  </div>
              </div>
          </div>
          <div className="secondarypush-1">
              <div className="secondarypush-hov_du_er_for_langt_v_k_-8">
                  {"Hov! Du er for langt væk :("}
              </div>
          </div>
          <div className="secondarypush-2">
              <div className="secondarypush-bev_g_dig_venligst_t_ttere_p_itu_for_at_bruge_findit_-4">
                  <div>{"Bevæg dig venligst tættere på ITU"}</div>
                  <div>for at bruge FindIT</div>
              </div>
          </div>
      </div>
    );
  }
};
